### ISSUE TITLE
Unable to use unicode string as keys for datrie.Trie

### ISSUE THREAD

**Issue by aleSuglia** [pytries/datrie#33]
Hi,

I'm using your library in order to save string which represents generic entity names (e.g., actors, places, genres, ...) as keys and for each key I have an integer identifier associated. 
I have created a minimal example which reproduces the error that I got: 

# Python3
```
import datrie
import string

trie = datrie.Trie(string.printable)

key_1 = "James Siegel"
key_2 = "Andor Lukáts"

trie[key_1] = 1
trie[key_2] = 2

# prints ['James Siegel'] - expected ['Andor Lukáts', 'James Siegel']
print(trie.keys())
```

# Python 2
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import datrie
import string

trie = datrie.Trie(string.printable)

key_1 = u'James Siegel'
key_2 = u'Andor Lukáts'

trie[key_1] = 1
trie[key_2] = 2

# prints ['James Siegel']
print trie.keys()

```
As you can see in the comment I expect to get a list of keys composed by *Andor Lukáts* and *James Siegel* but I got only the latter. If you try to remove the letter "á" from the key, the data structure correctly stores it.  What am I doing wrong?

Python version: 3.5.2 and 2.7.12
datrie version: 0.7.1

Thank you for your help.

Alessandro

**Comment by superbobry** [comment]
Hi Alessandro, 

The alphabet you've specified when constructing `datrie.Trie` does not contain `"á"`, therefore `key_1` is not inserted. Try this:

```python
trie = datrie.Trie(string.ascii_printable + "á")
```

Note, however, that the underlying `libdatrie` only supports alphabets of size no more than 255, therefore it isn't possible to store arbitrary Unicode strings at the moment.

**Comment by aleSuglia** [comment]
Hi,

thank you again for your answer.

I have the suspect that something is wrong with my alphabet definition. I'll try to extract all the needed characters from my entities and I'll use them as alphabet.

I hope that you will overcome this limitation as soon as possible. 

Alessandro

**Comment by superbobry** [comment]
> I hope that you will overcome this limitation as soon as possible.

Unfortunately, this isn't a limitation of the Python bindings but rather [the original C library](https://github.com/tlwg/libdatrie).

**Comment by aleSuglia** [comment]
Ok so this issue can be closed :)

Thank you again for your help.

**Comment by eromoe** [comment]
@superbobry Would you consider switch to a C library which support unicode ?
