### ISSUE TITLE
Create Nodes on Spaces

### ISSUE THREAD

**Issue by brunoalano** [pytries/datrie#37]
I've a problem, for example:

```python
trie = datrie.Trie(string.ascii_lowercase + ' ')
keys = ['something nice', 'something cool']
for i,k in enumerate(keys):
  trie[k] = i

trie.prefixes('something nice') # returns ['something nice']
```

But the `trie.prefixes`, should not return `['something', 'something nice']` in this case? Should I split the Sentence by spaces, and create a record for each splitted word?

**Comment by superbobry** [comment]
`datrie` does not do any special handling of whitespace characters. You specify `' '` as part of the alphabet therefore `'something nice'` is a valid word. 

To get the desired behaviour remove `' '` from the alphabet and split each sentence manually before inserting it into the trie.

**Comment by brunoalano** [comment]
@superbobry Thanks, no problem.

This is how I done it:

```python3
for tk in [ ' '.join(title.split()[0:i]) for i in range(1, len(title.split())) ]:
  if tk not in trie: trie[tk] = 0
```
