### ISSUE TITLE
How to support string longer than 256 ?

### ISSUE THREAD

**Issue by LubinLew** [pytries/datrie#45]
Hi,
I modified the code in function command_add_list(), change 256 to 2048,

`
command_add_list(..)
{
    char        line[2048];
   //....
    while (fgets (line, sizeof line, input)) {
        char       *key, *data;
        AlphaChar   key_alpha[2048];
        TrieData    data_val;
  //...
}
`
this works well in x86, but got core dumped in x64 when do the command 'trietool test list'.

**Comment by LubinLew** [comment]
change the 1024 to 2048 in function list_enum_func() seems to work well.

**Comment by superbobry** [comment]
Are you using the Python wrapper or [libdatrie](https://linux.thai.net/~thep/datrie/datrie.html) directly?
