### ISSUE TITLE
pytest-runner shouldn't be required for setup

### ISSUE THREAD

**Issue by yurivict** [pytries/datrie#58]
It de-facto builds fine without it.

Found the problem while creating the FreeBSD port.

**Comment by amirkdv** [comment]
I second this! This is unnecessarily complicating our build process (we depend on datrie through snakemake). pytest-runner is clearly only needed for development and belongs in `extras_require` rather than `setup_requires`.

## Current behavior

```
$ cat requirements.txt
snakemake
$ pip install -r requirements.txt
# fails, because pytest-runner is not installed for datrie

$ pip install pytest-runner
$ pip install -r requirements.txt
# succeeds
```

## Desired behavior

```
$ cat requirements.txt
snakemake
$ pip install -r requirements.txt
# should succeed
```

**Comment by amirkdv** [comment]
^ Full disclosure: strange; I encountered  the above problem yesterday and now cannot even reproduce it (building in isolated environments using docker, so there is no "memory" from previous pip invocations).
