### ISSUE TITLE
New release to PyPI required to support Python >= 3.7

### ISSUE THREAD

**Issue by cclauss** [pytries/datrie#68]
Related to #52 and html5lib/html5lib-python#417.

The last [release](https://github.com/pytries/datrie/releases) to [PyPI](https://pypi.org/project/datrie) was several years ago and does not include the fixes to support Python >= 3.7.

**Comment by bicycle1885** [comment]
Hi, is there any way to work around this problem? I'm using Python 3.7 and trying to install a package that depends on datrie, but it fails due to install error. Should I use an older Python version for now?

**Comment by cclauss** [comment]
__pip3 install git+https://github.com/pytries/datrie.git__

**Comment by frankier** [comment]
If you need to install it as a dependency on pypi, it's not possible to depend on github, I've release the HEAD as datrie-2019 on pypi as a stopgap in case this helps.

**Comment by bicycle1885** [comment]
Thank you. I wanted to use Snakemake, which depends on this package. I couldn't change dependencies of Snakemake so I used Python 3.6 this time.

**Comment by frankier** [comment]
Here is some relevant stuff on the Snakemake issue tracker in that case:

https://bitbucket.org/snakemake/snakemake/issues/934/installation-failed-in-python-37
https://bitbucket.org/snakemake/snakemake/pull-requests/388/get-datrie-from-datrie-2019-package-which/diff

**Comment by mivade** [comment]
Python 3.7 is now nearly a year old. Any chance we can get an update on this soon?

**Comment by kevinkle** [comment]
Can we get an update on this? I see the maintainers on the PyPI release as @kmike and @superbobry, or if the PyPI release isn't being maintained perhaps a confirmation so snakemake can adjust per @frankier

**Comment by mivade** [comment]
Python 3.7 was released over a year ago now. Can we please get a new release on PyPI?

**Comment by kmike** [comment]
Sorry for a delay. I've pushed 0.8 release to pypi.

**Comment by mivade** [comment]
Thanks, @kmike!

**Comment by kevinkle** [comment]
> Thanks, @kmike!

Likewise! Thanks @kmike
