### ISSUE TITLE
Get rid of all .c files in the repo

### ISSUE THREAD

**Issue by KOLANICH** [pytries/datrie#72]
They
1. are large, so they consume the space in the repo
2. contain the info already present in pyx files, so noone gonna read them
3. depend on cython version, so clutter logs and prs
4. are not generated automatcally currently, so it's easy to forget to generate them after a change

So it is proposed to
1. remove them all and ignore them, rewriting the whole repo history;
2. make them be generated during build.

**Comment by tacaswell** [comment]
I strongly disagree with proposal 1 as that will change the SHAs of all of the tags (and all of the commits).

I strongly agree with the second proposal.

**Comment by KOLANICH** [comment]
>I strongly disagree with proposal 1 as that will change the SHAs of all of the tags (and all of the commits)

IMHO it is totally not a problem for this repo. It is not an active repo with hundreds kf active contributors

**Comment by tacaswell** [comment]
No, but it is packaged by a number of down-stream packagers (at least anaconda, conda-forge and debian).  It is extremely bad practice to change the SHAs underneath released artifacts.

**Comment by KOLANICH** [comment]
> It is extremely bad practice to change the SHAs underneath released artifacts.

IMHO wasting space and bandwidth with garbage is even worse.

**Comment by tacaswell** [comment]
This is closed by #80 .  

Re-writing history is a non-starter.  If you want a full history without the c feel free to fork the project and manage porting any future work.
